version: '3.8'

services:
  ocr-bot:
    build: .
    container_name: telegram-bot
    restart: unless-stopped
    env_file:
      - .env
    working_dir: /app
    volumes:
      - .:/app
    command: python bot.py
